
// AUTOGENERATED RECURSION CONTENT
export const getRecursionCheckpointContent = (checkpointId, lang = 'cpp') => {
  const checkpoints = {
  "rec_cp1": {
    "title": "Re 1. Introduction to Recursion | Recursion Tree | Stack Space | Strivers A2Z DSA Course",
    "videoEmbedUrl": "https://www.youtube.com/embed/yVdKa8dnKiE?rel=0&modestbranding=1",
    "assessmentType": "mcq",
    "visualizationData": null,
    "challenge": {
      "title": "Checkpoint 1: Re 1. Introduction to Recursion | Recursion Tree | Stack Space | Strivers A2Z DSA Course",
      "difficulty": "Beginner",
      "description": "Watch the tutorial and complete the recursion challenge below.\n\nPay close attention to:\n1. Base Case (When does it stop?)\n2. Recursive Call (How does it progress?)\n3. Small Calculation (What work is done in this step?)",
      "hints": [
        "Always write the base case first.",
        "Think about what a single recursive call should return.",
        "Use the tree visualizer on the left if you get stuck."
      ],
      "boilerplates": {
        "cpp": "#include <iostream>\n#include <vector>\nusing namespace std;\n\nint solve(int n) {\n    // Write your recursive logic here\n    return 0;\n}",
        "java": "import java.util.*;\n\npublic class Solution {\n    public static int solve(int n) {\n        // Write your recursive logic here\n        return 0;\n    }\n}",
        "python": "def solve(n: int) -> int:\n    # Write your recursive logic here\n    pass",
        "javascript": "function solve(n) {\n    // Write your recursive logic here\n    \n}"
      },
      "testCases": [
        {
          "input": "3",
          "expected": "6",
          "isHidden": false
        },
        {
          "input": "4",
          "expected": "24",
          "isHidden": true
        }
      ],
      "solution": "// Implementation specific to Re 1. Introduction to Recursion | Recursion Tree | Stack Space | Strivers A2Z DSA Course"
    }
  },
  "rec_cp2": {
    "title": "Re 2. Problems on Recursion | Strivers A2Z DSA Course",
    "videoEmbedUrl": "https://www.youtube.com/embed/un6PLygfXrA?rel=0&modestbranding=1",
    "assessmentType": "mcq",
    "visualizationData": null,
    "challenge": {
      "title": "Checkpoint 2: Re 2. Problems on Recursion | Strivers A2Z DSA Course",
      "difficulty": "Beginner",
      "description": "Watch the tutorial and complete the recursion challenge below.\n\nPay close attention to:\n1. Base Case (When does it stop?)\n2. Recursive Call (How does it progress?)\n3. Small Calculation (What work is done in this step?)",
      "hints": [
        "Always write the base case first.",
        "Think about what a single recursive call should return.",
        "Use the tree visualizer on the left if you get stuck."
      ],
      "boilerplates": {
        "cpp": "#include <iostream>\n#include <vector>\nusing namespace std;\n\nint solve(int n) {\n    // Write your recursive logic here\n    return 0;\n}",
        "java": "import java.util.*;\n\npublic class Solution {\n    public static int solve(int n) {\n        // Write your recursive logic here\n        return 0;\n    }\n}",
        "python": "def solve(n: int) -> int:\n    # Write your recursive logic here\n    pass",
        "javascript": "function solve(n) {\n    // Write your recursive logic here\n    \n}"
      },
      "testCases": [
        {
          "input": "3",
          "expected": "6",
          "isHidden": false
        },
        {
          "input": "4",
          "expected": "24",
          "isHidden": true
        }
      ],
      "solution": "// Implementation specific to Re 2. Problems on Recursion | Strivers A2Z DSA Course"
    }
  },
  "rec_cp3": {
    "title": "Re 3. Parameterised and Functional Recursion | Strivers A2Z DSA Course",
    "videoEmbedUrl": "https://www.youtube.com/embed/69ZCDFy-OUo?rel=0&modestbranding=1",
    "assessmentType": "tracing",
    "visualizationData": null,
    "challenge": {
      "title": "Checkpoint 3: Re 3. Parameterised and Functional Recursion | Strivers A2Z DSA Course",
      "difficulty": "Beginner",
      "description": "Watch the tutorial and complete the recursion challenge below.\n\nPay close attention to:\n1. Base Case (When does it stop?)\n2. Recursive Call (How does it progress?)\n3. Small Calculation (What work is done in this step?)",
      "hints": [
        "Always write the base case first.",
        "Think about what a single recursive call should return.",
        "Use the tree visualizer on the left if you get stuck."
      ],
      "boilerplates": {
        "cpp": "#include <iostream>\n#include <vector>\nusing namespace std;\n\nint solve(int n) {\n    // Write your recursive logic here\n    return 0;\n}",
        "java": "import java.util.*;\n\npublic class Solution {\n    public static int solve(int n) {\n        // Write your recursive logic here\n        return 0;\n    }\n}",
        "python": "def solve(n: int) -> int:\n    # Write your recursive logic here\n    pass",
        "javascript": "function solve(n) {\n    // Write your recursive logic here\n    \n}"
      },
      "testCases": [
        {
          "input": "3",
          "expected": "6",
          "isHidden": false
        },
        {
          "input": "4",
          "expected": "24",
          "isHidden": true
        }
      ],
      "solution": "// Implementation specific to Re 3. Parameterised and Functional Recursion | Strivers A2Z DSA Course"
    }
  },
  "rec_cp4": {
    "title": "Re 4. Problems on Functional Recursion | Strivers A2Z DSA Course",
    "videoEmbedUrl": "https://www.youtube.com/embed/twuC1F6gLI8?rel=0&modestbranding=1",
    "assessmentType": "tracing",
    "visualizationData": null,
    "challenge": {
      "title": "Checkpoint 4: Re 4. Problems on Functional Recursion | Strivers A2Z DSA Course",
      "difficulty": "Beginner",
      "description": "Watch the tutorial and complete the recursion challenge below.\n\nPay close attention to:\n1. Base Case (When does it stop?)\n2. Recursive Call (How does it progress?)\n3. Small Calculation (What work is done in this step?)",
      "hints": [
        "Always write the base case first.",
        "Think about what a single recursive call should return.",
        "Use the tree visualizer on the left if you get stuck."
      ],
      "boilerplates": {
        "cpp": "#include <iostream>\n#include <vector>\nusing namespace std;\n\nint solve(int n) {\n    // Write your recursive logic here\n    return 0;\n}",
        "java": "import java.util.*;\n\npublic class Solution {\n    public static int solve(int n) {\n        // Write your recursive logic here\n        return 0;\n    }\n}",
        "python": "def solve(n: int) -> int:\n    # Write your recursive logic here\n    pass",
        "javascript": "function solve(n) {\n    // Write your recursive logic here\n    \n}"
      },
      "testCases": [
        {
          "input": "3",
          "expected": "6",
          "isHidden": false
        },
        {
          "input": "4",
          "expected": "24",
          "isHidden": true
        }
      ],
      "solution": "// Implementation specific to Re 4. Problems on Functional Recursion | Strivers A2Z DSA Course"
    }
  },
  "rec_cp5": {
    "title": "Re 5. Multiple Recursion Calls | Problems | Strivers A2Z DSA Course",
    "videoEmbedUrl": "https://www.youtube.com/embed/kvRjNm4rVBE?rel=0&modestbranding=1",
    "assessmentType": "coding",
    "visualizationData": {
      "title": "Factorial Tree",
      "nodes": [
        {
          "id": "1",
          "label": "fact(3)",
          "children": [
            "2"
          ]
        },
        {
          "id": "2",
          "label": "fact(2)",
          "children": [
            "3"
          ]
        },
        {
          "id": "3",
          "label": "fact(1)",
          "children": []
        }
      ],
      "steps": [
        {
          "text": "Call fact(3)",
          "activeNodes": [
            "1"
          ],
          "returningNodes": [],
          "variables": {
            "n": 3
          }
        },
        {
          "text": "Call fact(2)",
          "activeNodes": [
            "1",
            "2"
          ],
          "returningNodes": [],
          "variables": {
            "n": 2
          }
        },
        {
          "text": "Call fact(1)",
          "activeNodes": [
            "1",
            "2",
            "3"
          ],
          "returningNodes": [],
          "variables": {
            "n": 1
          }
        },
        {
          "text": "fact(1) returns 1 (Base Case)",
          "activeNodes": [
            "1",
            "2"
          ],
          "returningNodes": [
            "3"
          ],
          "variables": {
            "n": 1
          }
        },
        {
          "text": "fact(2) returns 2 * 1",
          "activeNodes": [
            "1"
          ],
          "returningNodes": [
            "2"
          ],
          "variables": {
            "n": 2
          }
        },
        {
          "text": "fact(3) returns 3 * 2",
          "activeNodes": [],
          "returningNodes": [
            "1"
          ],
          "variables": {
            "n": 3
          }
        }
      ]
    },
    "challenge": {
      "title": "Checkpoint 5: Re 5. Multiple Recursion Calls | Problems | Strivers A2Z DSA Course",
      "difficulty": "Beginner",
      "description": "Watch the tutorial and complete the recursion challenge below.\n\nPay close attention to:\n1. Base Case (When does it stop?)\n2. Recursive Call (How does it progress?)\n3. Small Calculation (What work is done in this step?)",
      "hints": [
        "Always write the base case first.",
        "Think about what a single recursive call should return.",
        "Use the tree visualizer on the left if you get stuck."
      ],
      "boilerplates": {
        "cpp": "#include <iostream>\n#include <vector>\nusing namespace std;\n\nint solve(int n) {\n    // Write your recursive logic here\n    return 0;\n}",
        "java": "import java.util.*;\n\npublic class Solution {\n    public static int solve(int n) {\n        // Write your recursive logic here\n        return 0;\n    }\n}",
        "python": "def solve(n: int) -> int:\n    # Write your recursive logic here\n    pass",
        "javascript": "function solve(n) {\n    // Write your recursive logic here\n    \n}"
      },
      "testCases": [
        {
          "input": "3",
          "expected": "6",
          "isHidden": false
        },
        {
          "input": "4",
          "expected": "24",
          "isHidden": true
        }
      ],
      "solution": "// Implementation specific to Re 5. Multiple Recursion Calls | Problems | Strivers A2Z DSA Course"
    }
  },
  "rec_cp6": {
    "title": "L6. Recursion on Subsequences | Printing Subsequences",
    "videoEmbedUrl": "https://www.youtube.com/embed/AxNNVECce8c?rel=0&modestbranding=1",
    "assessmentType": "coding",
    "visualizationData": {
      "title": "Array Reversal Tree",
      "nodes": [
        {
          "id": "1",
          "label": "rev(arr, 0, 4)",
          "children": [
            "2"
          ]
        },
        {
          "id": "2",
          "label": "rev(arr, 1, 3)",
          "children": [
            "3"
          ]
        },
        {
          "id": "3",
          "label": "rev(arr, 2, 2)",
          "children": []
        }
      ],
      "steps": [
        {
          "text": "Swap index 0 and 4",
          "activeNodes": [
            "1"
          ],
          "returningNodes": []
        },
        {
          "text": "Swap index 1 and 3",
          "activeNodes": [
            "1",
            "2"
          ],
          "returningNodes": []
        },
        {
          "text": "Base Case: i >= j",
          "activeNodes": [
            "1",
            "2",
            "3"
          ],
          "returningNodes": []
        },
        {
          "text": "Return",
          "activeNodes": [
            "1",
            "2"
          ],
          "returningNodes": [
            "3"
          ]
        },
        {
          "text": "Return",
          "activeNodes": [
            "1"
          ],
          "returningNodes": [
            "2"
          ]
        },
        {
          "text": "Done",
          "activeNodes": [],
          "returningNodes": [
            "1"
          ]
        }
      ]
    },
    "challenge": {
      "title": "Checkpoint 6: L6. Recursion on Subsequences | Printing Subsequences",
      "difficulty": "Intermediate",
      "description": "Watch the tutorial and complete the recursion challenge below.\n\nPay close attention to:\n1. Base Case (When does it stop?)\n2. Recursive Call (How does it progress?)\n3. Small Calculation (What work is done in this step?)",
      "hints": [
        "Always write the base case first.",
        "Think about what a single recursive call should return.",
        "Use the tree visualizer on the left if you get stuck."
      ],
      "boilerplates": {
        "cpp": "#include <iostream>\n#include <vector>\nusing namespace std;\n\nint solve(int n) {\n    // Write your recursive logic here\n    return 0;\n}",
        "java": "import java.util.*;\n\npublic class Solution {\n    public static int solve(int n) {\n        // Write your recursive logic here\n        return 0;\n    }\n}",
        "python": "def solve(n: int) -> int:\n    # Write your recursive logic here\n    pass",
        "javascript": "function solve(n) {\n    // Write your recursive logic here\n    \n}"
      },
      "testCases": [
        {
          "input": "3",
          "expected": "6",
          "isHidden": false
        },
        {
          "input": "4",
          "expected": "24",
          "isHidden": true
        }
      ],
      "solution": "// Implementation specific to L6. Recursion on Subsequences | Printing Subsequences"
    }
  },
  "rec_cp7": {
    "title": "L7. All Kind of Patterns in Recursion | Print All | Print one | Count",
    "videoEmbedUrl": "https://www.youtube.com/embed/eQCS_v3bw0Q?rel=0&modestbranding=1",
    "assessmentType": "coding",
    "visualizationData": {
      "title": "Array Reversal Tree",
      "nodes": [
        {
          "id": "1",
          "label": "rev(arr, 0, 4)",
          "children": [
            "2"
          ]
        },
        {
          "id": "2",
          "label": "rev(arr, 1, 3)",
          "children": [
            "3"
          ]
        },
        {
          "id": "3",
          "label": "rev(arr, 2, 2)",
          "children": []
        }
      ],
      "steps": [
        {
          "text": "Swap index 0 and 4",
          "activeNodes": [
            "1"
          ],
          "returningNodes": []
        },
        {
          "text": "Swap index 1 and 3",
          "activeNodes": [
            "1",
            "2"
          ],
          "returningNodes": []
        },
        {
          "text": "Base Case: i >= j",
          "activeNodes": [
            "1",
            "2",
            "3"
          ],
          "returningNodes": []
        },
        {
          "text": "Return",
          "activeNodes": [
            "1",
            "2"
          ],
          "returningNodes": [
            "3"
          ]
        },
        {
          "text": "Return",
          "activeNodes": [
            "1"
          ],
          "returningNodes": [
            "2"
          ]
        },
        {
          "text": "Done",
          "activeNodes": [],
          "returningNodes": [
            "1"
          ]
        }
      ]
    },
    "challenge": {
      "title": "Checkpoint 7: L7. All Kind of Patterns in Recursion | Print All | Print one | Count",
      "difficulty": "Intermediate",
      "description": "Watch the tutorial and complete the recursion challenge below.\n\nPay close attention to:\n1. Base Case (When does it stop?)\n2. Recursive Call (How does it progress?)\n3. Small Calculation (What work is done in this step?)",
      "hints": [
        "Always write the base case first.",
        "Think about what a single recursive call should return.",
        "Use the tree visualizer on the left if you get stuck."
      ],
      "boilerplates": {
        "cpp": "#include <iostream>\n#include <vector>\nusing namespace std;\n\nint solve(int n) {\n    // Write your recursive logic here\n    return 0;\n}",
        "java": "import java.util.*;\n\npublic class Solution {\n    public static int solve(int n) {\n        // Write your recursive logic here\n        return 0;\n    }\n}",
        "python": "def solve(n: int) -> int:\n    # Write your recursive logic here\n    pass",
        "javascript": "function solve(n) {\n    // Write your recursive logic here\n    \n}"
      },
      "testCases": [
        {
          "input": "3",
          "expected": "6",
          "isHidden": false
        },
        {
          "input": "4",
          "expected": "24",
          "isHidden": true
        }
      ],
      "solution": "// Implementation specific to L7. All Kind of Patterns in Recursion | Print All | Print one | Count"
    }
  },
  "rec_cp8": {
    "title": "Merge Sort | Algorithm | Pseudocode | Dry Run | Code | Strivers A2Z DSA Course",
    "videoEmbedUrl": "https://www.youtube.com/embed/ogjf7ORKfd8?rel=0&modestbranding=1",
    "assessmentType": "coding",
    "visualizationData": null,
    "challenge": {
      "title": "Checkpoint 8: Merge Sort | Algorithm | Pseudocode | Dry Run | Code | Strivers A2Z DSA Course",
      "difficulty": "Intermediate",
      "description": "Watch the tutorial and complete the recursion challenge below.\n\nPay close attention to:\n1. Base Case (When does it stop?)\n2. Recursive Call (How does it progress?)\n3. Small Calculation (What work is done in this step?)",
      "hints": [
        "Always write the base case first.",
        "Think about what a single recursive call should return.",
        "Use the tree visualizer on the left if you get stuck."
      ],
      "boilerplates": {
        "cpp": "#include <iostream>\n#include <vector>\nusing namespace std;\n\nint solve(int n) {\n    // Write your recursive logic here\n    return 0;\n}",
        "java": "import java.util.*;\n\npublic class Solution {\n    public static int solve(int n) {\n        // Write your recursive logic here\n        return 0;\n    }\n}",
        "python": "def solve(n: int) -> int:\n    # Write your recursive logic here\n    pass",
        "javascript": "function solve(n) {\n    // Write your recursive logic here\n    \n}"
      },
      "testCases": [
        {
          "input": "3",
          "expected": "6",
          "isHidden": false
        },
        {
          "input": "4",
          "expected": "24",
          "isHidden": true
        }
      ],
      "solution": "// Implementation specific to Merge Sort | Algorithm | Pseudocode | Dry Run | Code | Strivers A2Z DSA Course"
    }
  },
  "rec_cp9": {
    "title": "Quick Sort For Beginners | Strivers A2Z DSA Course",
    "videoEmbedUrl": "https://www.youtube.com/embed/WIrA4YexLRQ?rel=0&modestbranding=1",
    "assessmentType": "coding",
    "visualizationData": null,
    "challenge": {
      "title": "Checkpoint 9: Quick Sort For Beginners | Strivers A2Z DSA Course",
      "difficulty": "Intermediate",
      "description": "Watch the tutorial and complete the recursion challenge below.\n\nPay close attention to:\n1. Base Case (When does it stop?)\n2. Recursive Call (How does it progress?)\n3. Small Calculation (What work is done in this step?)",
      "hints": [
        "Always write the base case first.",
        "Think about what a single recursive call should return.",
        "Use the tree visualizer on the left if you get stuck."
      ],
      "boilerplates": {
        "cpp": "#include <iostream>\n#include <vector>\nusing namespace std;\n\nint solve(int n) {\n    // Write your recursive logic here\n    return 0;\n}",
        "java": "import java.util.*;\n\npublic class Solution {\n    public static int solve(int n) {\n        // Write your recursive logic here\n        return 0;\n    }\n}",
        "python": "def solve(n: int) -> int:\n    # Write your recursive logic here\n    pass",
        "javascript": "function solve(n) {\n    // Write your recursive logic here\n    \n}"
      },
      "testCases": [
        {
          "input": "3",
          "expected": "6",
          "isHidden": false
        },
        {
          "input": "4",
          "expected": "24",
          "isHidden": true
        }
      ],
      "solution": "// Implementation specific to Quick Sort For Beginners | Strivers A2Z DSA Course"
    }
  },
  "rec_cp10": {
    "title": "L8. Combination Sum | Recursion | Leetcode | C++ | Java",
    "videoEmbedUrl": "https://www.youtube.com/embed/OyZFFqQtu98?rel=0&modestbranding=1",
    "assessmentType": "coding",
    "visualizationData": null,
    "challenge": {
      "title": "Checkpoint 10: L8. Combination Sum | Recursion | Leetcode | C++ | Java",
      "difficulty": "Intermediate",
      "description": "Watch the tutorial and complete the recursion challenge below.\n\nPay close attention to:\n1. Base Case (When does it stop?)\n2. Recursive Call (How does it progress?)\n3. Small Calculation (What work is done in this step?)",
      "hints": [
        "Always write the base case first.",
        "Think about what a single recursive call should return.",
        "Use the tree visualizer on the left if you get stuck."
      ],
      "boilerplates": {
        "cpp": "#include <iostream>\n#include <vector>\nusing namespace std;\n\nint solve(int n) {\n    // Write your recursive logic here\n    return 0;\n}",
        "java": "import java.util.*;\n\npublic class Solution {\n    public static int solve(int n) {\n        // Write your recursive logic here\n        return 0;\n    }\n}",
        "python": "def solve(n: int) -> int:\n    # Write your recursive logic here\n    pass",
        "javascript": "function solve(n) {\n    // Write your recursive logic here\n    \n}"
      },
      "testCases": [
        {
          "input": "3",
          "expected": "6",
          "isHidden": false
        },
        {
          "input": "4",
          "expected": "24",
          "isHidden": true
        }
      ],
      "solution": "// Implementation specific to L8. Combination Sum | Recursion | Leetcode | C++ | Java"
    }
  },
  "rec_cp11": {
    "title": "L9. Combination Sum II | Leetcode | Recursion | Java | C++",
    "videoEmbedUrl": "https://www.youtube.com/embed/G1fRTGRxXU8?rel=0&modestbranding=1",
    "assessmentType": "coding",
    "visualizationData": null,
    "challenge": {
      "title": "Checkpoint 11: L9. Combination Sum II | Leetcode | Recursion | Java | C++",
      "difficulty": "Intermediate",
      "description": "Watch the tutorial and complete the recursion challenge below.\n\nPay close attention to:\n1. Base Case (When does it stop?)\n2. Recursive Call (How does it progress?)\n3. Small Calculation (What work is done in this step?)",
      "hints": [
        "Always write the base case first.",
        "Think about what a single recursive call should return.",
        "Use the tree visualizer on the left if you get stuck."
      ],
      "boilerplates": {
        "cpp": "#include <iostream>\n#include <vector>\nusing namespace std;\n\nint solve(int n) {\n    // Write your recursive logic here\n    return 0;\n}",
        "java": "import java.util.*;\n\npublic class Solution {\n    public static int solve(int n) {\n        // Write your recursive logic here\n        return 0;\n    }\n}",
        "python": "def solve(n: int) -> int:\n    # Write your recursive logic here\n    pass",
        "javascript": "function solve(n) {\n    // Write your recursive logic here\n    \n}"
      },
      "testCases": [
        {
          "input": "3",
          "expected": "6",
          "isHidden": false
        },
        {
          "input": "4",
          "expected": "24",
          "isHidden": true
        }
      ],
      "solution": "// Implementation specific to L9. Combination Sum II | Leetcode | Recursion | Java | C++"
    }
  },
  "rec_cp12": {
    "title": "L10. Subset Sum I | Recursion | C++ | Java",
    "videoEmbedUrl": "https://www.youtube.com/embed/rYkfBRtMJr8?rel=0&modestbranding=1",
    "assessmentType": "coding",
    "visualizationData": null,
    "challenge": {
      "title": "Checkpoint 12: L10. Subset Sum I | Recursion | C++ | Java",
      "difficulty": "Intermediate",
      "description": "Watch the tutorial and complete the recursion challenge below.\n\nPay close attention to:\n1. Base Case (When does it stop?)\n2. Recursive Call (How does it progress?)\n3. Small Calculation (What work is done in this step?)",
      "hints": [
        "Always write the base case first.",
        "Think about what a single recursive call should return.",
        "Use the tree visualizer on the left if you get stuck."
      ],
      "boilerplates": {
        "cpp": "#include <iostream>\n#include <vector>\nusing namespace std;\n\nint solve(int n) {\n    // Write your recursive logic here\n    return 0;\n}",
        "java": "import java.util.*;\n\npublic class Solution {\n    public static int solve(int n) {\n        // Write your recursive logic here\n        return 0;\n    }\n}",
        "python": "def solve(n: int) -> int:\n    # Write your recursive logic here\n    pass",
        "javascript": "function solve(n) {\n    // Write your recursive logic here\n    \n}"
      },
      "testCases": [
        {
          "input": "3",
          "expected": "6",
          "isHidden": false
        },
        {
          "input": "4",
          "expected": "24",
          "isHidden": true
        }
      ],
      "solution": "// Implementation specific to L10. Subset Sum I | Recursion | C++ | Java"
    }
  },
  "rec_cp13": {
    "title": "L11. Subset Sum II | Leetcode | Recursion",
    "videoEmbedUrl": "https://www.youtube.com/embed/RIn3gOkbhQE?rel=0&modestbranding=1",
    "assessmentType": "coding",
    "visualizationData": null,
    "challenge": {
      "title": "Checkpoint 13: L11. Subset Sum II | Leetcode | Recursion",
      "difficulty": "Advanced",
      "description": "Watch the tutorial and complete the recursion challenge below.\n\nPay close attention to:\n1. Base Case (When does it stop?)\n2. Recursive Call (How does it progress?)\n3. Small Calculation (What work is done in this step?)",
      "hints": [
        "Always write the base case first.",
        "Think about what a single recursive call should return.",
        "Use the tree visualizer on the left if you get stuck."
      ],
      "boilerplates": {
        "cpp": "#include <iostream>\n#include <vector>\nusing namespace std;\n\nint solve(int n) {\n    // Write your recursive logic here\n    return 0;\n}",
        "java": "import java.util.*;\n\npublic class Solution {\n    public static int solve(int n) {\n        // Write your recursive logic here\n        return 0;\n    }\n}",
        "python": "def solve(n: int) -> int:\n    # Write your recursive logic here\n    pass",
        "javascript": "function solve(n) {\n    // Write your recursive logic here\n    \n}"
      },
      "testCases": [
        {
          "input": "3",
          "expected": "6",
          "isHidden": false
        },
        {
          "input": "4",
          "expected": "24",
          "isHidden": true
        }
      ],
      "solution": "// Implementation specific to L11. Subset Sum II | Leetcode | Recursion"
    }
  },
  "rec_cp14": {
    "title": "L12. Print all Permutations of a String/Array | Recursion | Approach - 1",
    "videoEmbedUrl": "https://www.youtube.com/embed/YK78FU5Ffjw?rel=0&modestbranding=1",
    "assessmentType": "coding",
    "visualizationData": null,
    "challenge": {
      "title": "Checkpoint 14: L12. Print all Permutations of a String/Array | Recursion | Approach - 1",
      "difficulty": "Advanced",
      "description": "Watch the tutorial and complete the recursion challenge below.\n\nPay close attention to:\n1. Base Case (When does it stop?)\n2. Recursive Call (How does it progress?)\n3. Small Calculation (What work is done in this step?)",
      "hints": [
        "Always write the base case first.",
        "Think about what a single recursive call should return.",
        "Use the tree visualizer on the left if you get stuck."
      ],
      "boilerplates": {
        "cpp": "#include <iostream>\n#include <vector>\nusing namespace std;\n\nint solve(int n) {\n    // Write your recursive logic here\n    return 0;\n}",
        "java": "import java.util.*;\n\npublic class Solution {\n    public static int solve(int n) {\n        // Write your recursive logic here\n        return 0;\n    }\n}",
        "python": "def solve(n: int) -> int:\n    # Write your recursive logic here\n    pass",
        "javascript": "function solve(n) {\n    // Write your recursive logic here\n    \n}"
      },
      "testCases": [
        {
          "input": "3",
          "expected": "6",
          "isHidden": false
        },
        {
          "input": "4",
          "expected": "24",
          "isHidden": true
        }
      ],
      "solution": "// Implementation specific to L12. Print all Permutations of a String/Array | Recursion | Approach - 1"
    }
  },
  "rec_cp15": {
    "title": "L13. Print all Permutations of a String/Array | Recursion | Approach - 2",
    "videoEmbedUrl": "https://www.youtube.com/embed/f2ic2Rsc9pU?rel=0&modestbranding=1",
    "assessmentType": "coding",
    "visualizationData": null,
    "challenge": {
      "title": "Checkpoint 15: L13. Print all Permutations of a String/Array | Recursion | Approach - 2",
      "difficulty": "Advanced",
      "description": "Watch the tutorial and complete the recursion challenge below.\n\nPay close attention to:\n1. Base Case (When does it stop?)\n2. Recursive Call (How does it progress?)\n3. Small Calculation (What work is done in this step?)",
      "hints": [
        "Always write the base case first.",
        "Think about what a single recursive call should return.",
        "Use the tree visualizer on the left if you get stuck."
      ],
      "boilerplates": {
        "cpp": "#include <iostream>\n#include <vector>\nusing namespace std;\n\nint solve(int n) {\n    // Write your recursive logic here\n    return 0;\n}",
        "java": "import java.util.*;\n\npublic class Solution {\n    public static int solve(int n) {\n        // Write your recursive logic here\n        return 0;\n    }\n}",
        "python": "def solve(n: int) -> int:\n    # Write your recursive logic here\n    pass",
        "javascript": "function solve(n) {\n    // Write your recursive logic here\n    \n}"
      },
      "testCases": [
        {
          "input": "3",
          "expected": "6",
          "isHidden": false
        },
        {
          "input": "4",
          "expected": "24",
          "isHidden": true
        }
      ],
      "solution": "// Implementation specific to L13. Print all Permutations of a String/Array | Recursion | Approach - 2"
    }
  },
  "rec_cp16": {
    "title": "L14. N-Queens | Leetcode Hard | Backtracking",
    "videoEmbedUrl": "https://www.youtube.com/embed/i05Ju7AftcM?rel=0&modestbranding=1",
    "assessmentType": "coding",
    "visualizationData": null,
    "challenge": {
      "title": "Checkpoint 16: L14. N-Queens | Leetcode Hard | Backtracking",
      "difficulty": "Advanced",
      "description": "Watch the tutorial and complete the recursion challenge below.\n\nPay close attention to:\n1. Base Case (When does it stop?)\n2. Recursive Call (How does it progress?)\n3. Small Calculation (What work is done in this step?)",
      "hints": [
        "Always write the base case first.",
        "Think about what a single recursive call should return.",
        "Use the tree visualizer on the left if you get stuck."
      ],
      "boilerplates": {
        "cpp": "#include <iostream>\n#include <vector>\nusing namespace std;\n\nint solve(int n) {\n    // Write your recursive logic here\n    return 0;\n}",
        "java": "import java.util.*;\n\npublic class Solution {\n    public static int solve(int n) {\n        // Write your recursive logic here\n        return 0;\n    }\n}",
        "python": "def solve(n: int) -> int:\n    # Write your recursive logic here\n    pass",
        "javascript": "function solve(n) {\n    // Write your recursive logic here\n    \n}"
      },
      "testCases": [
        {
          "input": "3",
          "expected": "6",
          "isHidden": false
        },
        {
          "input": "4",
          "expected": "24",
          "isHidden": true
        }
      ],
      "solution": "// Implementation specific to L14. N-Queens | Leetcode Hard | Backtracking"
    }
  },
  "rec_cp17": {
    "title": "L15. Sudoko Solver | Backtracking",
    "videoEmbedUrl": "https://www.youtube.com/embed/FWAIf_EVUKE?rel=0&modestbranding=1",
    "assessmentType": "coding",
    "visualizationData": null,
    "challenge": {
      "title": "Checkpoint 17: L15. Sudoko Solver | Backtracking",
      "difficulty": "Advanced",
      "description": "Watch the tutorial and complete the recursion challenge below.\n\nPay close attention to:\n1. Base Case (When does it stop?)\n2. Recursive Call (How does it progress?)\n3. Small Calculation (What work is done in this step?)",
      "hints": [
        "Always write the base case first.",
        "Think about what a single recursive call should return.",
        "Use the tree visualizer on the left if you get stuck."
      ],
      "boilerplates": {
        "cpp": "#include <iostream>\n#include <vector>\nusing namespace std;\n\nint solve(int n) {\n    // Write your recursive logic here\n    return 0;\n}",
        "java": "import java.util.*;\n\npublic class Solution {\n    public static int solve(int n) {\n        // Write your recursive logic here\n        return 0;\n    }\n}",
        "python": "def solve(n: int) -> int:\n    # Write your recursive logic here\n    pass",
        "javascript": "function solve(n) {\n    // Write your recursive logic here\n    \n}"
      },
      "testCases": [
        {
          "input": "3",
          "expected": "6",
          "isHidden": false
        },
        {
          "input": "4",
          "expected": "24",
          "isHidden": true
        }
      ],
      "solution": "// Implementation specific to L15. Sudoko Solver | Backtracking"
    }
  },
  "rec_cp18": {
    "title": "L16. M-Coloring Problem | Backtracking",
    "videoEmbedUrl": "https://www.youtube.com/embed/wuVwUK25Rfc?rel=0&modestbranding=1",
    "assessmentType": "coding",
    "visualizationData": null,
    "challenge": {
      "title": "Checkpoint 18: L16. M-Coloring Problem | Backtracking",
      "difficulty": "Advanced",
      "description": "Watch the tutorial and complete the recursion challenge below.\n\nPay close attention to:\n1. Base Case (When does it stop?)\n2. Recursive Call (How does it progress?)\n3. Small Calculation (What work is done in this step?)",
      "hints": [
        "Always write the base case first.",
        "Think about what a single recursive call should return.",
        "Use the tree visualizer on the left if you get stuck."
      ],
      "boilerplates": {
        "cpp": "#include <iostream>\n#include <vector>\nusing namespace std;\n\nint solve(int n) {\n    // Write your recursive logic here\n    return 0;\n}",
        "java": "import java.util.*;\n\npublic class Solution {\n    public static int solve(int n) {\n        // Write your recursive logic here\n        return 0;\n    }\n}",
        "python": "def solve(n: int) -> int:\n    # Write your recursive logic here\n    pass",
        "javascript": "function solve(n) {\n    // Write your recursive logic here\n    \n}"
      },
      "testCases": [
        {
          "input": "3",
          "expected": "6",
          "isHidden": false
        },
        {
          "input": "4",
          "expected": "24",
          "isHidden": true
        }
      ],
      "solution": "// Implementation specific to L16. M-Coloring Problem | Backtracking"
    }
  },
  "rec_cp19": {
    "title": "L17. Palindrome Partitioning | Leetcode | Recursion | C++ | Java",
    "videoEmbedUrl": "https://www.youtube.com/embed/WBgsABoClE0?rel=0&modestbranding=1",
    "assessmentType": "coding",
    "visualizationData": null,
    "challenge": {
      "title": "Checkpoint 19: L17. Palindrome Partitioning | Leetcode | Recursion | C++ | Java",
      "difficulty": "Advanced",
      "description": "Watch the tutorial and complete the recursion challenge below.\n\nPay close attention to:\n1. Base Case (When does it stop?)\n2. Recursive Call (How does it progress?)\n3. Small Calculation (What work is done in this step?)",
      "hints": [
        "Always write the base case first.",
        "Think about what a single recursive call should return.",
        "Use the tree visualizer on the left if you get stuck."
      ],
      "boilerplates": {
        "cpp": "#include <iostream>\n#include <vector>\nusing namespace std;\n\nint solve(int n) {\n    // Write your recursive logic here\n    return 0;\n}",
        "java": "import java.util.*;\n\npublic class Solution {\n    public static int solve(int n) {\n        // Write your recursive logic here\n        return 0;\n    }\n}",
        "python": "def solve(n: int) -> int:\n    # Write your recursive logic here\n    pass",
        "javascript": "function solve(n) {\n    // Write your recursive logic here\n    \n}"
      },
      "testCases": [
        {
          "input": "3",
          "expected": "6",
          "isHidden": false
        },
        {
          "input": "4",
          "expected": "24",
          "isHidden": true
        }
      ],
      "solution": "// Implementation specific to L17. Palindrome Partitioning | Leetcode | Recursion | C++ | Java"
    }
  },
  "rec_cp20": {
    "title": "L19. Rat in A Maze | Backtracking",
    "videoEmbedUrl": "https://www.youtube.com/embed/bLGZhJlt4y0?rel=0&modestbranding=1",
    "assessmentType": "coding",
    "visualizationData": null,
    "challenge": {
      "title": "Checkpoint 20: L19. Rat in A Maze | Backtracking",
      "difficulty": "Advanced",
      "description": "Watch the tutorial and complete the recursion challenge below.\n\nPay close attention to:\n1. Base Case (When does it stop?)\n2. Recursive Call (How does it progress?)\n3. Small Calculation (What work is done in this step?)",
      "hints": [
        "Always write the base case first.",
        "Think about what a single recursive call should return.",
        "Use the tree visualizer on the left if you get stuck."
      ],
      "boilerplates": {
        "cpp": "#include <iostream>\n#include <vector>\nusing namespace std;\n\nint solve(int n) {\n    // Write your recursive logic here\n    return 0;\n}",
        "java": "import java.util.*;\n\npublic class Solution {\n    public static int solve(int n) {\n        // Write your recursive logic here\n        return 0;\n    }\n}",
        "python": "def solve(n: int) -> int:\n    # Write your recursive logic here\n    pass",
        "javascript": "function solve(n) {\n    // Write your recursive logic here\n    \n}"
      },
      "testCases": [
        {
          "input": "3",
          "expected": "6",
          "isHidden": false
        },
        {
          "input": "4",
          "expected": "24",
          "isHidden": true
        }
      ],
      "solution": "// Implementation specific to L19. Rat in A Maze | Backtracking"
    }
  },
  "rec_cp21": {
    "title": "L18. K-th Permutation Sequence | Leetcode",
    "videoEmbedUrl": "https://www.youtube.com/embed/wT7gcXLYoao?rel=0&modestbranding=1",
    "assessmentType": "coding",
    "visualizationData": null,
    "challenge": {
      "title": "Checkpoint 21: L18. K-th Permutation Sequence | Leetcode",
      "difficulty": "Advanced",
      "description": "Watch the tutorial and complete the recursion challenge below.\n\nPay close attention to:\n1. Base Case (When does it stop?)\n2. Recursive Call (How does it progress?)\n3. Small Calculation (What work is done in this step?)",
      "hints": [
        "Always write the base case first.",
        "Think about what a single recursive call should return.",
        "Use the tree visualizer on the left if you get stuck."
      ],
      "boilerplates": {
        "cpp": "#include <iostream>\n#include <vector>\nusing namespace std;\n\nint solve(int n) {\n    // Write your recursive logic here\n    return 0;\n}",
        "java": "import java.util.*;\n\npublic class Solution {\n    public static int solve(int n) {\n        // Write your recursive logic here\n        return 0;\n    }\n}",
        "python": "def solve(n: int) -> int:\n    # Write your recursive logic here\n    pass",
        "javascript": "function solve(n) {\n    // Write your recursive logic here\n    \n}"
      },
      "testCases": [
        {
          "input": "3",
          "expected": "6",
          "isHidden": false
        },
        {
          "input": "4",
          "expected": "24",
          "isHidden": true
        }
      ],
      "solution": "// Implementation specific to L18. K-th Permutation Sequence | Leetcode"
    }
  },
  "rec_cp22": {
    "title": "Count Inversions in an Array | Brute and Optimal",
    "videoEmbedUrl": "https://www.youtube.com/embed/AseUmwVNaoY?rel=0&modestbranding=1",
    "assessmentType": "coding",
    "visualizationData": null,
    "challenge": {
      "title": "Checkpoint 22: Count Inversions in an Array | Brute and Optimal",
      "difficulty": "Advanced",
      "description": "Watch the tutorial and complete the recursion challenge below.\n\nPay close attention to:\n1. Base Case (When does it stop?)\n2. Recursive Call (How does it progress?)\n3. Small Calculation (What work is done in this step?)",
      "hints": [
        "Always write the base case first.",
        "Think about what a single recursive call should return.",
        "Use the tree visualizer on the left if you get stuck."
      ],
      "boilerplates": {
        "cpp": "#include <iostream>\n#include <vector>\nusing namespace std;\n\nint solve(int n) {\n    // Write your recursive logic here\n    return 0;\n}",
        "java": "import java.util.*;\n\npublic class Solution {\n    public static int solve(int n) {\n        // Write your recursive logic here\n        return 0;\n    }\n}",
        "python": "def solve(n: int) -> int:\n    # Write your recursive logic here\n    pass",
        "javascript": "function solve(n) {\n    // Write your recursive logic here\n    \n}"
      },
      "testCases": [
        {
          "input": "3",
          "expected": "6",
          "isHidden": false
        },
        {
          "input": "4",
          "expected": "24",
          "isHidden": true
        }
      ],
      "solution": "// Implementation specific to Count Inversions in an Array | Brute and Optimal"
    }
  }
};
  const cp = checkpoints[checkpointId] || checkpoints['rec_cp1'];
  
  return {
    title: cp.title,
    subtitle: cp.subtitle || '',
    videoEmbedUrl: cp.videoEmbedUrl,
    assessmentType: cp.assessmentType,
    visualizationData: cp.visualizationData,
    challengeTitle: cp.challenge.title,
    challengeDescription: cp.challenge.description,
    approach: cp.challenge.approach || '',
    code: cp.challenge.solution || '',
    editorBoilerplate: cp.challenge.boilerplates[lang] || cp.challenge.boilerplates['cpp'] || '',
    testCases: cp.challenge.testCases,
    functionName: cp.challenge.functionName || 'solve',
    hints: cp.challenge.hints,
    constraints: cp.challenge.constraints || 'None',
    hasVideo: true
  };
};
