const fs = require('fs');
const path = require('path');

const playlistData = require('C:\\\\Users\\\\Tarun Shivhare\\\\.gemini\\\\antigravity\\\\brain\\\\fcf3e3ca-a8b3-4e50-87d0-b09d5d959eb2\\\\scratch\\\\recursion_playlist.json');

const checkpoints = {};

playlistData.forEach((video, idx) => {
  const cpNum = idx + 1;
  const isBasics = cpNum <= 5;
  const isIntermediate = cpNum > 5 && cpNum <= 12;
  
  let assessmentType = 'coding';
  if (cpNum === 1 || cpNum === 2) assessmentType = 'mcq';
  if (cpNum === 3 || cpNum === 4) assessmentType = 'tracing';

  let visDataObj = null;
  if (cpNum === 5) {
    visDataObj = {
      title: "Factorial Tree",
      nodes: [
        { id: '1', label: 'fact(3)', children: ['2'] },
        { id: '2', label: 'fact(2)', children: ['3'] },
        { id: '3', label: 'fact(1)', children: [] }
      ],
      steps: [
        { text: "Call fact(3)", activeNodes: ['1'], returningNodes: [], variables: { n: 3 } },
        { text: "Call fact(2)", activeNodes: ['1', '2'], returningNodes: [], variables: { n: 2 } },
        { text: "Call fact(1)", activeNodes: ['1', '2', '3'], returningNodes: [], variables: { n: 1 } },
        { text: "fact(1) returns 1 (Base Case)", activeNodes: ['1', '2'], returningNodes: ['3'], variables: { n: 1 } },
        { text: "fact(2) returns 2 * 1", activeNodes: ['1'], returningNodes: ['2'], variables: { n: 2 } },
        { text: "fact(3) returns 3 * 2", activeNodes: [], returningNodes: ['1'], variables: { n: 3 } }
      ]
    };
  } else if (cpNum === 6 || cpNum === 7) {
    visDataObj = {
      title: "Array Reversal Tree",
      nodes: [
        { id: '1', label: 'rev(arr, 0, 4)', children: ['2'] },
        { id: '2', label: 'rev(arr, 1, 3)', children: ['3'] },
        { id: '3', label: 'rev(arr, 2, 2)', children: [] }
      ],
      steps: [
        { text: "Swap index 0 and 4", activeNodes: ['1'], returningNodes: [] },
        { text: "Swap index 1 and 3", activeNodes: ['1', '2'], returningNodes: [] },
        { text: "Base Case: i >= j", activeNodes: ['1', '2', '3'], returningNodes: [] },
        { text: "Return", activeNodes: ['1', '2'], returningNodes: ['3'] },
        { text: "Return", activeNodes: ['1'], returningNodes: ['2'] },
        { text: "Done", activeNodes: [], returningNodes: ['1'] }
      ]
    };
  }

  checkpoints[`rec_cp${cpNum}`] = {
    title: video.title,
    videoEmbedUrl: `https://www.youtube.com/embed/${video.videoId}?rel=0&modestbranding=1`,
    assessmentType: assessmentType,
    visualizationData: visDataObj,
    challenge: {
      title: `Checkpoint ${cpNum}: ${video.title}`,
      difficulty: isBasics ? 'Beginner' : isIntermediate ? 'Intermediate' : 'Advanced',
      description: "Watch the tutorial and complete the recursion challenge below.\n\nPay close attention to:\n1. Base Case (When does it stop?)\n2. Recursive Call (How does it progress?)\n3. Small Calculation (What work is done in this step?)",
      hints: [
        "Always write the base case first.",
        "Think about what a single recursive call should return.",
        "Use the tree visualizer on the left if you get stuck."
      ],
      boilerplates: {
        cpp: "#include <iostream>\n#include <vector>\nusing namespace std;\n\nint solve(int n) {\n    // Write your recursive logic here\n    return 0;\n}",
        java: "import java.util.*;\n\npublic class Solution {\n    public static int solve(int n) {\n        // Write your recursive logic here\n        return 0;\n    }\n}",
        python: "def solve(n: int) -> int:\n    # Write your recursive logic here\n    pass",
        javascript: "function solve(n) {\n    // Write your recursive logic here\n    \n}"
      },
      testCases: [
        { input: "3", expected: "6", isHidden: false },
        { input: "4", expected: "24", isHidden: true }
      ],
      solution: `// Implementation specific to ${video.title}`
    }
  };
});

const content = `
// AUTOGENERATED RECURSION CONTENT
export const getRecursionCheckpointContent = (checkpointId, lang = 'cpp') => {
  const checkpoints = ${JSON.stringify(checkpoints, null, 2)};
  const cp = checkpoints[checkpointId] || checkpoints['rec_cp1'];
  
  return {
    title: cp.title,
    subtitle: cp.subtitle || '',
    videoEmbedUrl: cp.videoEmbedUrl,
    assessmentType: cp.assessmentType,
    visualizationData: cp.visualizationData,
    challengeTitle: cp.challenge.title,
    challengeDescription: cp.challenge.description,
    approach: cp.challenge.approach || '',
    code: cp.challenge.solution || '',
    editorBoilerplate: cp.challenge.boilerplates[lang] || cp.challenge.boilerplates['cpp'] || '',
    testCases: cp.challenge.testCases,
    functionName: cp.challenge.functionName || 'solve',
    hints: cp.challenge.hints,
    constraints: cp.challenge.constraints || 'None',
    hasVideo: true
  };
};
`;

const outputPath = path.join(__dirname, '..', 'client', 'src', 'utils', 'recursionContent.js');
fs.writeFileSync(outputPath, content);
console.log('Recursion content generated at:', outputPath);
